### ISSUE TITLE
Panics on a fresh device in local mode

### ISSUE THREAD

**Issue by robertgzr** [balenablocks/connector#22]
```
[Logs]    [10/5/2020, 7:13:35 PM] Restarting service 'connector sha256:5c237eec5a5eed3dc95ac86b8abdd25370976d5da59c928fc16045e7e67f0594'
[Logs]    [10/5/2020, 7:12:33 PM] [connector] Traceback (most recent call last):
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 98, in get
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     rt = self.__get_by_raw_query(raw_query)
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 75, in __get_by_raw_query
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     raise exceptions.ReleaseNotFound(raw_query)
[Logs]    [10/5/2020, 7:12:33 PM] [connector] balena.exceptions.ReleaseNotFound: $filter=startswith(commit, 'None')
[Logs]    [10/5/2020, 7:12:33 PM] [connector]
[Logs]    [10/5/2020, 7:12:33 PM] [connector] During handling of the above exception, another exception occurred:
[Logs]    [10/5/2020, 7:12:33 PM] [connector]
[Logs]    [10/5/2020, 7:12:33 PM] [connector] Traceback (most recent call last):
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "./autowire.py", line 82, in <module>
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     config = autowire.GetConfig()
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "./autowire.py", line 48, in GetConfig
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     services = self.GetServices()
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "./autowire.py", line 24, in GetServices
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     release = self.balena.models.release.get(commit)
[Logs]    [10/5/2020, 7:12:33 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 105, in get
[Logs]    [10/5/2020, 7:12:33 PM] [connector]     raise exceptions.ReleaseNotFound(commit_or_id)
[Logs]    [10/5/2020, 7:12:33 PM] [connector] balena.exceptions.ReleaseNotFound: None
[Logs]    [10/5/2020, 7:13:35 PM] [connector]
[Logs]    [10/5/2020, 7:13:35 PM] [connector] Changing hostname to aa5da0b
[Logs]    [10/5/2020, 7:13:35 PM] [connector] Generating config
[Logs]    [10/5/2020, 7:13:35 PM] [connector] /root/.local/lib/python3.5/site-packages/pluginbase.py:439: CryptographyDeprecationWarning: Python 3.5 support will be dropped in the next release ofcryptography. Please upgrade your Python.
[Logs]    [10/5/2020, 7:13:35 PM] [connector]   fromlist, level)
[Logs]    [10/5/2020, 7:13:37 PM] [connector] balenablocks/connector
[Logs]    [10/5/2020, 7:13:37 PM] [connector] ----------------------
[Logs]    [10/5/2020, 7:13:37 PM] [connector] Intelligently connecting data sources with data sinks
[Logs]    [10/5/2020, 7:13:38 PM] [connector] Traceback (most recent call last):
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 98, in get
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     rt = self.__get_by_raw_query(raw_query)
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 75, in __get_by_raw_query
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     raise exceptions.ReleaseNotFound(raw_query)
[Logs]    [10/5/2020, 7:13:38 PM] [connector] balena.exceptions.ReleaseNotFound: $filter=startswith(commit, 'None')
[Logs]    [10/5/2020, 7:13:38 PM] [connector]
[Logs]    [10/5/2020, 7:13:38 PM] [connector] During handling of the above exception, another exception occurred:
[Logs]    [10/5/2020, 7:13:38 PM] [connector]
[Logs]    [10/5/2020, 7:13:38 PM] [connector] Traceback (most recent call last):
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "./autowire.py", line 82, in <module>
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     config = autowire.GetConfig()
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "./autowire.py", line 48, in GetConfig
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     services = self.GetServices()
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "./autowire.py", line 24, in GetServices
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     release = self.balena.models.release.get(commit)
[Logs]    [10/5/2020, 7:13:38 PM] [connector]   File "/root/.local/lib/python3.5/site-packages/balena/models/release.py", line 105, in get
[Logs]    [10/5/2020, 7:13:38 PM] [connector]     raise exceptions.ReleaseNotFound(commit_or_id)
[Logs]    [10/5/2020, 7:13:38 PM] [connector] balena.exceptions.ReleaseNotFound: None
[Logs]    [10/5/2020, 7:13:39 PM] Service exited 'connector sha256:5c237eec5a5eed3dc95ac86b8abdd25370976d5da59c928fc16045e7e67f0594'
```

**Comment by robertgzr** [comment]
@phil-d-wilson could you go via the supervisor api? https://github.com/balena-io/balena-supervisor/blob/master/docs/API.md#get-v2applicationsstate

**Comment by phil-d-wilson** [comment]
@robertgzr We need to find the ports exposed as well as the services on the device.

**Comment by robertgzr** [comment]
@phil-d-wilson not sure if I want to recommend going there but you can get that via the docker socket :P
